### ISSUE TITLE
Third-party apps / extensions: fluentcms-teaser

### ISSUE THREAD

**Issue by bashu** [edoburu/django-fluent-contents#54]
Thanks for django-fluent-[contents|pages], here is my small contribution https://github.com/bashu/fluentcms-teaser

PS: fluentcms-filer (django-file integration) and fluentcms-suit (django-suit integration) will be ready soon =)

**Comment by vdboor** [comment]
Wonderful. thanks for making that a plugin.

I had a similar plugin (called announcement item) but teaser is a much better name.
One suggestion: make the description a PluginHtmlField. In my experience, users want to be able to place links there. I'm tempted to make some wysiwyg-hint like `PluginHtmlField(style='simple')` because it shouldn't have to show all toolbar buttons.

**Comment by bashu** [comment]
@vdboor done
