### ISSUE TITLE
Backwards incompatible changes not documented in changelog.

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-fluent-contents#67]
`fluent_contents.plugins.text.appsettings` was removed. We were importing this in our code, which broke with the latest version, and there's no mention in the changelog.

Looks like these were moved to `fluent_contents.appsettings`, but at least a mention in the docs and ideally keeping it available at the old location with a deprecation warning would be great.

**Comment by vdboor** [comment]
hmm good point. I didn't expect this to be a backwards incompatible issue, as I mostly saw it was internal code. You're right it should have been mentioned.

Typically I'm in favor of keeping a stub present so old code still works. Would you still think it's relevant to update this? (I presume not since you've already fixed the code?)

**Comment by mrmachine** [comment]
I think it's worth mentioning in the docs / release notes, and if it's not too much trouble, an import from the old location with a deprecation warning. I don't what the chances are of this affecting anyone else, but it's possible that someone could be importing the plugin's `appsettings` and using an older pinned version of `django-fluent-contents` that will break if / when they upgrade.

**Comment by vdboor** [comment]
I've added the message. Better late then sorry..
